version: "2"

run:
  tests: false
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - modernize
    - revive
    - godot
    - misspell
    - gomoddirectives
    - goprintffuncname
    - noctx
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - wrapcheck

  exclusions:
    generated: lax
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx

  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
