ALTER TABLE public_keys ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE matches ALTER COLUMN game_id DROP NOT NULL;
ALTER TABLE public_keys ALTER COLUMN name DROP NOT NULL;
ALTER TABLE rankings ALTER COLUMN elo DROP NOT NULL;
